#OBJS specifies which files to compile as part of the project
OBJS = src/chip8.c src/main.c

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = chip8.o

#This is the target that compiles our executable
all : $(OBJS)
	gcc $(OBJS) -w -lSDL2 -o $(OBJ_NAME) -Wall -g
